/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeIndexImport } from './routes/_home/index'
import { Route as PetsUpgradeIndexImport } from './routes/pets/upgrade/index'
import { Route as EconomySpeedupsIndexImport } from './routes/economy/speedups/index'
import { Route as EconomyItems2IndexImport } from './routes/economy/items2/index'
import { Route as EconomyItemsIndexImport } from './routes/economy/items/index'
import { Route as EconomyBundlesIndexImport } from './routes/economy/bundles/index'

// Create/Update Routes

const HomeIndexRoute = HomeIndexImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PetsUpgradeIndexRoute = PetsUpgradeIndexImport.update({
  id: '/pets/upgrade/',
  path: '/pets/upgrade/',
  getParentRoute: () => rootRoute,
} as any)

const EconomySpeedupsIndexRoute = EconomySpeedupsIndexImport.update({
  id: '/economy/speedups/',
  path: '/economy/speedups/',
  getParentRoute: () => rootRoute,
} as any)

const EconomyItems2IndexRoute = EconomyItems2IndexImport.update({
  id: '/economy/items2/',
  path: '/economy/items2/',
  getParentRoute: () => rootRoute,
} as any)

const EconomyItemsIndexRoute = EconomyItemsIndexImport.update({
  id: '/economy/items/',
  path: '/economy/items/',
  getParentRoute: () => rootRoute,
} as any)

const EconomyBundlesIndexRoute = EconomyBundlesIndexImport.update({
  id: '/economy/bundles/',
  path: '/economy/bundles/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/economy/bundles/': {
      id: '/economy/bundles/'
      path: '/economy/bundles'
      fullPath: '/economy/bundles'
      preLoaderRoute: typeof EconomyBundlesIndexImport
      parentRoute: typeof rootRoute
    }
    '/economy/items/': {
      id: '/economy/items/'
      path: '/economy/items'
      fullPath: '/economy/items'
      preLoaderRoute: typeof EconomyItemsIndexImport
      parentRoute: typeof rootRoute
    }
    '/economy/items2/': {
      id: '/economy/items2/'
      path: '/economy/items2'
      fullPath: '/economy/items2'
      preLoaderRoute: typeof EconomyItems2IndexImport
      parentRoute: typeof rootRoute
    }
    '/economy/speedups/': {
      id: '/economy/speedups/'
      path: '/economy/speedups'
      fullPath: '/economy/speedups'
      preLoaderRoute: typeof EconomySpeedupsIndexImport
      parentRoute: typeof rootRoute
    }
    '/pets/upgrade/': {
      id: '/pets/upgrade/'
      path: '/pets/upgrade'
      fullPath: '/pets/upgrade'
      preLoaderRoute: typeof PetsUpgradeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof HomeIndexRoute
  '/economy/bundles': typeof EconomyBundlesIndexRoute
  '/economy/items': typeof EconomyItemsIndexRoute
  '/economy/items2': typeof EconomyItems2IndexRoute
  '/economy/speedups': typeof EconomySpeedupsIndexRoute
  '/pets/upgrade': typeof PetsUpgradeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof HomeIndexRoute
  '/economy/bundles': typeof EconomyBundlesIndexRoute
  '/economy/items': typeof EconomyItemsIndexRoute
  '/economy/items2': typeof EconomyItems2IndexRoute
  '/economy/speedups': typeof EconomySpeedupsIndexRoute
  '/pets/upgrade': typeof PetsUpgradeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_home/': typeof HomeIndexRoute
  '/economy/bundles/': typeof EconomyBundlesIndexRoute
  '/economy/items/': typeof EconomyItemsIndexRoute
  '/economy/items2/': typeof EconomyItems2IndexRoute
  '/economy/speedups/': typeof EconomySpeedupsIndexRoute
  '/pets/upgrade/': typeof PetsUpgradeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/economy/bundles'
    | '/economy/items'
    | '/economy/items2'
    | '/economy/speedups'
    | '/pets/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/economy/bundles'
    | '/economy/items'
    | '/economy/items2'
    | '/economy/speedups'
    | '/pets/upgrade'
  id:
    | '__root__'
    | '/_home/'
    | '/economy/bundles/'
    | '/economy/items/'
    | '/economy/items2/'
    | '/economy/speedups/'
    | '/pets/upgrade/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  HomeIndexRoute: typeof HomeIndexRoute
  EconomyBundlesIndexRoute: typeof EconomyBundlesIndexRoute
  EconomyItemsIndexRoute: typeof EconomyItemsIndexRoute
  EconomyItems2IndexRoute: typeof EconomyItems2IndexRoute
  EconomySpeedupsIndexRoute: typeof EconomySpeedupsIndexRoute
  PetsUpgradeIndexRoute: typeof PetsUpgradeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  HomeIndexRoute: HomeIndexRoute,
  EconomyBundlesIndexRoute: EconomyBundlesIndexRoute,
  EconomyItemsIndexRoute: EconomyItemsIndexRoute,
  EconomyItems2IndexRoute: EconomyItems2IndexRoute,
  EconomySpeedupsIndexRoute: EconomySpeedupsIndexRoute,
  PetsUpgradeIndexRoute: PetsUpgradeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_home/",
        "/economy/bundles/",
        "/economy/items/",
        "/economy/items2/",
        "/economy/speedups/",
        "/pets/upgrade/"
      ]
    },
    "/_home/": {
      "filePath": "_home/index.tsx"
    },
    "/economy/bundles/": {
      "filePath": "economy/bundles/index.tsx"
    },
    "/economy/items/": {
      "filePath": "economy/items/index.tsx"
    },
    "/economy/items2/": {
      "filePath": "economy/items2/index.tsx"
    },
    "/economy/speedups/": {
      "filePath": "economy/speedups/index.tsx"
    },
    "/pets/upgrade/": {
      "filePath": "pets/upgrade/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
